In [64]:
import psycopg2
import sqlalchemy as sq
import pandas as pd
import numpy as np
import mariadb
import dask.dataframe as dd
import json
import os
import shutil
import subprocess
from pathlib import Path
import pyodbc

In [2]:
conn_lims = pyodbc.connect("Driver={SQL Server};"
                            "Server=192.168.5.18\CROPNUT;"
                            "Database=cropnuts;"
                            "uid=thomasTsuma;pwd=GR^KX$uRe9#JwLc6")

<>:2: SyntaxWarning: invalid escape sequence '\C'
<>:2: SyntaxWarning: invalid escape sequence '\C'
C:\Users\tommy\AppData\Local\Temp\ipykernel_26608\232176420.py:2: SyntaxWarning: invalid escape sequence '\C'
  "Server=192.168.5.18\CROPNUT;"

In [3]:
water_df = pd.read_sql("select sample_code, batch_date, crop_name, chemical_name, result, unit_name from SampleResults where group_name='Water Analysis'",con=conn_lims)

C:\Users\tommy\AppData\Local\Temp\ipykernel_22132\3641743634.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  water_df = pd.read_sql("select sample_code, batch_date, crop_name, growth_name, chemical_name, result, unit_name from SampleResults where group_name='Water Analysis'",con=conn_lims)

In [4]:
water_df.to_csv("input/water_samples.csv")

In [65]:
water_df = pd.read_csv("input/water_samples.csv")

C:\Users\tommy\AppData\Local\Temp\ipykernel_26608\1772474551.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  water_df = pd.read_csv("input/water_samples.csv")

In [66]:
water_df

,Unnamed: 0,sample_code,batch_date,crop_name,growth_name,chemical_name,result,unit_name
0,0,CA335WA0010,2019-04-18 00:00:00.000,Reverse Osmosis Use,NaN,pH,8.27,NaN
1,1,CD026WA2057,2019-05-07 00:00:00.000,Reverse Osmosis Use,NaN,pH,8.25,NaN
2,2,CB012WA0052,2012-07-19 00:00:00.000,Irrigation (FAO),NaN,pH,7.25,NaN
3,3,CB012WA0052,2012-07-19 00:00:00.000,Irrigation (FAO),NaN,Electrical Conductivity,0.15,mS cm -1
4,4,CB012WA0052,2012-07-19 00:00:00.000,Irrigation (FAO),NaN,Ammonium,< 0.01,ppm
...,...,...,...,...,...,...,...,...
1169863,1169863,CA028WA0130,2024-05-21 14:27:00.000,Drinking (W.H.O.),NaN,Nitrate N,5.90,ppm
1169864,1169864,CB387WA0006,2024-05-21 09:32:00.000,Drinking (W.H.O.),NaN,Phosphorus,0.012,ppm
1169865,1169865,CB387WA0006,2024-05-21 09:32:00.000,Drinking (W.H.O.),NaN,Sulphur,5.27,ppm
1169866,1169866,CB387WA0006,2024-05-21 09:32:00.000,Drinking (W.H.O.),NaN,Iron,0.013,ppm
1169867,1169867,CB387WA0006,2024-05-21 09:32:00.000,Drinking (W.H.O.),NaN,Manganese,< 0.01,ppm

In [67]:
water_df['crop_name'].describe()

count               1169868
unique                   53
top       Drinking (W.H.O.)
freq                 661021
Name: crop_name, dtype: object

In [68]:
water_df = water_df.loc[~(water_df['result'] == "ND") ]
water_df = water_df.loc[~(water_df['result'] == "Detected") ]

In [69]:
water_df = water_df.dropna(subset="result")

In [70]:
water_df

,Unnamed: 0,sample_code,batch_date,crop_name,growth_name,chemical_name,result,unit_name
0,0,CA335WA0010,2019-04-18 00:00:00.000,Reverse Osmosis Use,NaN,pH,8.27,NaN
1,1,CD026WA2057,2019-05-07 00:00:00.000,Reverse Osmosis Use,NaN,pH,8.25,NaN
2,2,CB012WA0052,2012-07-19 00:00:00.000,Irrigation (FAO),NaN,pH,7.25,NaN
3,3,CB012WA0052,2012-07-19 00:00:00.000,Irrigation (FAO),NaN,Electrical Conductivity,0.15,mS cm -1
4,4,CB012WA0052,2012-07-19 00:00:00.000,Irrigation (FAO),NaN,Ammonium,< 0.01,ppm
...,...,...,...,...,...,...,...,...
1169863,1169863,CA028WA0130,2024-05-21 14:27:00.000,Drinking (W.H.O.),NaN,Nitrate N,5.90,ppm
1169864,1169864,CB387WA0006,2024-05-21 09:32:00.000,Drinking (W.H.O.),NaN,Phosphorus,0.012,ppm
1169865,1169865,CB387WA0006,2024-05-21 09:32:00.000,Drinking (W.H.O.),NaN,Sulphur,5.27,ppm
1169866,1169866,CB387WA0006,2024-05-21 09:32:00.000,Drinking (W.H.O.),NaN,Iron,0.013,ppm
1169867,1169867,CB387WA0006,2024-05-21 09:32:00.000,Drinking (W.H.O.),NaN,Manganese,< 0.01,ppm

In [71]:
water_df['result'] = [ float(i.replace("<","").replace(">","").strip()) for i in water_df['result']]

In [72]:
water_df['unit_name'] = [ str(i).strip() for i in water_df['unit_name'].values ]

In [73]:
water_df['chemical_name'] = [ str(i).lower().replace(" ","_").replace("(","").replace(")","").replace(".","").strip() for i in water_df['chemical_name'].values ]

In [74]:
water_df = water_df.loc[~(water_df['result'] < 0)]

In [75]:
water_df = water_df.loc[~(water_df['unit_name'] == "nan")]

In [ ]:
water_df.groupby("crop_name").sum()

In [81]:
[ i for i in water_df.columns]

['Unnamed: 0',
 'sample_code',
 'batch_date',
 'crop_name',
 'growth_name',
 'chemical_name',
 'result',
 'unit_name']

In [88]:
water_df.to_csv("input/water_analysis_cleaned.csv")

In [55]:
params_count_dict = {}
params_dict = {}

In [56]:
for i in water_df['crop_name'].unique():
    print(i)
    temp = water_df.loc[water_df['crop_name'] == i].pivot_table(columns="chemical_name", index="sample_code", values="result")
    temp_count = pd.DataFrame(temp.isna().sum(axis=0))

    print(len(temp_count[temp_count != len(temp)].index))
    params_count_dict[i] = temp.isna().sum(axis=0).to_dict()
    params_dict[i] = temp_count[temp_count != len(temp)].index

Irrigation (FAO)
90
Reverse Osmosis Use
83
Reverse Osmosis (WHO Drinking Water Guidelines)
59
Drinking (W.H.O.)
110
Post Harvest
69
Drinking Water (NEMA)
46
Domestic Use
54
Fresh water
31
KSEAS 12 2018 Treated Potable
75
Effluent
4
Irrigation
39
Drinking (FAO)
32
Distilled Water
47
Effluent Water (NEMA)
7
HCl Acid
22
Natural water quality for aquatic life
9
KSEAS 12 2018 Untreated Potable
62
KSEAS 153 2018 Packaged
59
Drinking (KEBS)
46
Swimming Water
23
Irrigation Water (NEMA)
24
(Distilled Water)
48
Fish Extracts
21
Fish Farming
36
Fruit Juice
29
Pack House
28
NEMA waste water
30
NEMA Effluent into Environment
34
NEMA Effluent
13
Treated Potable Water (EAS 12:2018)
41
Nitric Acid
13
Drinking (WHO 2107 4th edition)
27
Boiler Scales
14
Process Water
32
Deionised Water
28
Tea Extract
24
Plain Water
25
Acetic Acid
13
Concentrate Water
23
Reagent Water
6
KS 2846:2020 Construction Water
23
Raw Water
31
NEMA3 Effluent into Environment
13
NEMA6 Treated Effluent into Environ
1
NEMA5 Effluent into Public Sewer
2

In [61]:
pd.DataFrame(params_count_dict).to_csv("output/parameters_count_per_crop_name.csv")

In [62]:
df = pd.DataFrame()
for crop, params in params_dict.items():
    _ = pd.DataFrame(columns=[i for i in params])
    for col in _.columns:
        _[col] = [True]
    _['crop_name'] = crop
    df = pd.concat([df,_])
df.to_csv("output/parameters_per_crop.csv")

C:\Users\tommy\AppData\Local\Temp\ipykernel_26608\1487365853.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  _['crop_name'] = crop

,aerobic_mesophilic_count,aluminium,ammonium,arsenic,barium,bicarbonate,bod,boron,cadmium,calcium,...,ph,total_bacterial_count,total_residual_chlorine,chromium-6,dissolved_chlorine,dissolved_oxygen,residual__free_chlorine,sludge_content,residiue_on_evaporation,sulphuric_acid
0,True,True,True,True,True,True,True,True,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,True,True,True,True,True,True,True,True,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,True,True,True,True,True,True,True,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,True,True,True,True,True,True,True,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,True,True,True,True,True,True,True,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,True,True,True,True,NaN,True,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,True,True,True,True,True,NaN,True,True,True,...,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,True,NaN,NaN,True,NaN,True,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,True,True,True,True,True,True,True,True,True,...,NaN,NaN,NaN,True,True,True,True,True,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,True,True,True,NaN,True,NaN,True,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,True,True,NaN,True,NaN,True,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,True,True,NaN,True,True,True,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN
0,NaN,NaN,True,NaN,NaN,NaN,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,True,NaN,True,NaN,NaN,NaN,True,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,True,True,True,True,True,True,True,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN
0,NaN,True,True,True,True,True,True,True,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN
0,NaN,True,True,True,True,True,NaN,True,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,...,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,True,NaN,NaN,True,True,True,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,True,True,NaN,True,NaN,True,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
0,NaN,NaN,True,NaN,NaN,True,NaN,True,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,True,True,NaN,True,NaN,True,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,True,True,NaN,True,NaN,True,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,True,NaN,NaN,True,NaN,True,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,True,NaN,NaN,True,True,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,True,True,NaN,True,True,True,True,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,True,NaN,NaN,NaN,True,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,True,True,True,True,True,NaN,True,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,True,NaN,NaN,NaN,True,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,True,NaN,NaN,True,NaN,True,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,True,NaN,NaN,NaN,NaN,NaN,True,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,True,True,NaN,True,NaN,True,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,True,NaN,NaN,True,NaN,True,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,True,True,NaN,NaN,True,NaN,True,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,True,NaN,NaN,True,NaN,True,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,True,NaN,NaN,NaN,True,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,True,NaN,True,NaN,NaN,NaN,True,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,True,NaN,NaN,True,NaN,True,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,True,NaN,NaN,True,NaN,True,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,True,NaN,NaN,NaN,True,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN